baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "GROOVIN' HIGH"
description = 'The Real Book and the materiality of musical practice'
author = 'Hern√°n Adasme'
theme = 'PaperMod'

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/home'
    weight = 10
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menu.main]]
    name = 'Episodes'
    pageRef = '/episodes'
    weight = 30